### ISSUE TITLE
Update Documentation 

### ISSUE THREAD

**Issue by ayushk1804** [pbdsce/advaith-website#23]
This repo does not have user-friendly documentation. It would be best to have a readme file with the following sections:

- About 
- Build Instructions
  - Development Guide
  - Production Steps
- Contribution Guidelines
- PR layout

**Comment by Saikat-Chattoraj** [comment]
I would like to work on this issue. Kindly assign this to me.

**Comment by ayushk1804** [comment]
Sure, go ahead!

**Comment by SparshKesari** [comment]
@Saikat-Chattoraj. Are you working on it? Please update.

**Comment by Saikat-Chattoraj** [comment]
Yes. I am currently working on it.
