### ISSUE TITLE
Readme images dont load properly

### ISSUE THREAD

**Issue by Saikat-Chattoraj** [pbdsce/advaith-website#38]
It seems that the images added to the readme dont point to a valid URL.

**Comment by ayushk1804** [comment]
That seems to be correct. Kindly work on this issue.

**Comment by Saikat-Chattoraj** [comment]
Updated Readme #38

**Comment by SparshKesari** [comment]
@Saikat-Chattoraj this issue is not still resolved. Look into it
Suggestions: Make an asset folder and load the images from there

**Comment by SparshKesari** [comment]
closed with pr #40
